FROM registry.cn-hangzhou.aliyuncs.com/xhsheng/github_dockerfile:torch1_4_mink040_tf113

RUN apt-get update && \
	  pip install -i https://pypi.tuna.tsinghua.edu.cn/simple torch-points3d==1.1.1 && \
	  apt-get clean && \
    apt-get autoremove	
