FROM pytorch/pytorch:1.4-cuda10.1-cudnn7-devel

RUN rm /etc/apt/sources.list.d/cuda.list && rm /etc/apt/sources.list.d/nvidia-ml.list && \
    sed -i 's/archive.ubuntu.com/mirrors.ustc.edu.cn/g' /etc/apt/sources.list

RUN apt-get update && \
    apt install -y openssh-server openssh-client && \
    apt install -y libopenblas-dev && \
    pip install MinkowskiEngine==0.4.0 && \
    apt install -y libgl1-mesa-glx &&\
    apt-get clean && \
    apt-get autoremove
