FROM pytorch/pytorch:1.4-cuda10.1-cudnn7-devel

RUN rm /etc/apt/sources.list.d/cuda.list && rm /etc/apt/sources.list.d/nvidia-ml.list && \
	  sed -i 's/archive.ubuntu.com/mirrors.ustc.edu.cn/g' /etc/apt/sources.list

RUN apt-get update && \
	  apt install -y openssh-server openssh-client && \
    apt install -y libopenblas-dev && \
    pip install MinkowskiEngine==0.4.0 && \
	  apt install -y libgl1-mesa-glx &&\
    pip install open3d-python && \
	  pip install opencv-python && \
	  pip install tensorboardX &&\
    pip install tensorflow==1.13.1 &&\
    pip install pandas && \
	  apt-get clean && \
    apt-get autoremove
